### ISSUE TITLE
menu item after edit category

### ISSUE THREAD

**Issue by crossplatformcode** [gruz/MenuAry#1]
After menu generation if add/edit description of a category that is in the list of category in the plugin, corresponding menu item changes and get a lower level without show in it's menu setting and without any change in parent.

**Comment by gruz** [comment]
Can you describe with an example? I've read twice and didn't catch :-)

**Comment by crossplatformcode** [comment]
I create two category: category1, category2.Then with menuary I create a menu with these categories and menuary creates two menu item in the root of the menu. Then i go to content/category/category2 and add description for this category. Then go to menu and see change level of corresponding menu item and in the site view this menu item is hidden. I suggest with edit category, corresponding generated menu may be corrupted.

**Comment by gruz** [comment]
Please check the latest version from here and let me know so I can release a stable version: http://gruz.org.ua/en/extensions/menuary-automatic-menu/1-1-6-rc.html

**Comment by crossplatformcode** [comment]
This new version works correctly without no issue in category content change.
Thanks for release new version.
